import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Grand Cureg Family</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="w-full h-screen flex flex-col items-center justify-center">
        <h1 className="font-bold text-4xl">Grand Cureg Family</h1>
      </main>

    </div>
  )
}

export default Home
